### ISSUE TITLE
$params appears as a multidimensional array when Invoking REST Method

### ISSUE THREAD

**Issue by melabadi** [swisscom/PowerGRR#21] opened 2018-01-17 15:29 UTC
In PowerGRR.psm1, L:2330 - $params has two nested cells instead of a list with the parameters: One with the Uri and TimeoutSec, and the other one with the Headers. I believe this causes a problem during the binding.

This issue was noticed when I tried to call Get-GRRHunt.

When debugging at said line, this powershell line works:
`Invoke-RestMethod -Uri $Params[0].Uri -TimeoutSec $Params[0].TimeoutSec -Headers $Params[1].Headers`

I would love to have everyone's input on this. Perhaps I'm doing it wrong.

**Comment by Karneades** [comment] 2018-01-18 18:32
Thanks for your issue.

I can't reproduce it currently. But I'm more than happy to help. Which version of PowerGRR and which OS do you use?

We use "parameter splatting" - this means, we do not have to explicitly use the parameters in the call to `Invoke-RestMethod`, instead we can use that hashtable for passing all these parameters at once. We build our parameters ($params) with all the needed values, one of them is the headers parameter (which is again an hashtable for itself), and then pass the whole $params to the `Invoke-RestMethod` on L:2522.

For example the following command works for me with the most current version:
` Get-GRRHunt -Credential $cred -Count 5`

**Comment by melabadi** [comment] 2018-01-19 15:18
Thank you for answering! Using PSVersion 5.1.14393.1944 and Microsoft Windows NT 10.0.14393.0!
For some reason, the problem fixed by itself (implying there a problem to start with), but I encountered at times an issue concerning $params not being initialized before adding hashes. Such errors appeared during `Invoke-GRRRequest` when hashes were being added - see L:2215.

Somehow, adding `$params = @{}` right after `$ret = "" (L:2191)` fixed this issue, but it is weird behavior, especially considering how I `Import-Module PowerGRR -force` after every change.

Would love to know if I am not the only one with said issue!

Thanks again!

**Comment by Karneades** [comment] 2018-01-19 23:29
Thanks for your infos. I added the initialization for this variable in both `Invoke-GRRRequest` and `Get-GRRSession`. However, I didn't get any errors in the past. Furthermore, we use strict mode latest and that didn't complain either. I pushed the changes to Github (not yet to PowerShellGallery).

If you still have issues, please provide the PowerGRR version and the PowerGRR command you use.

**Comment by Karneades** [comment] 2018-02-07 15:13
@Se1ecto Did you get any errors after the fix? Otherwise, I would close the issue.

**Closed as completed** 2018-02-13 17:48 UTC
